/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyek_pbo;
import proyek_pbo.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
        

/**
 *
 * @author kylex
 */
public class Alokasi_Alok extends javax.swing.JFrame {
    List<Mahasiswa> mahas = new ArrayList<Mahasiswa>();
    List<Asrama> asrm = new ArrayList<Asrama>();
    DbHandler a = new DbHandler();
    int max_mahas;
    int max_asrm;
    int idx_mahas = 0;
    int idx_asrm = 0;
    /**
     * Creates new form Alokasi_Home
     */
    public Alokasi_Alok() {
        initComponents();
        jLabel4.setText("");
        refresh();
        refreshbox();
        
        
        
       
        
           
        }
    
    public void refreshbox(){
            
        this.combox_asrama.removeAllItems();
        this.combox_mahas.removeAllItems();
        this.combox_kamar.removeAllItems();
        refresh();
        idx_mahas = 0;
        idx_asrm = 0;
        if(max_mahas>0){
        while(idx_mahas<max_mahas){
            a.connect("localhost", "db_asrama", "pbo", "pbo");
            if(a.getallocbynim(mahas.get(idx_mahas).getNim()) == null){
                this.combox_mahas.addItem(mahas.get(idx_mahas).getNama());
                
            }
            a.disconnect();
            
            idx_mahas++;    
        }
        }
        
         if(max_asrm > 0){
        while(idx_asrm<max_asrm){
            this.combox_asrama.addItem(asrm.get(idx_asrm).getNama_asrama());
            idx_asrm++;    
        }
         
        
        
        }
        
        
    }
        
    
     public void refresh(){
        a.connect("localhost", "db_asrama", "pbo", "pbo");
        this.mahas = a.getallmahas();
        this.max_mahas = a.counter;
        this.asrm = a.getallasrama();
        this.max_asrm = a.counter;
        a.disconnect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combox_mahas = new javax.swing.JComboBox<>();
        combox_asrama = new javax.swing.JComboBox<>();
        combox_kamar = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        combox_mahas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        combox_asrama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combox_asrama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combox_asramaActionPerformed(evt);
            }
        });

        combox_kamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Asrama :");

        jLabel2.setText("No Kamar :");

        jLabel3.setText("Nama Mahasiswa :");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setText("Success ! ");

        jLabel5.setText(" Alokasi Asrama");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(combox_mahas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combox_asrama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combox_kamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(160, 160, 160))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(135, 135, 135))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combox_mahas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combox_asrama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combox_kamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(73, 73, 73)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(this.combox_asrama.getSelectedItem() == null || this.combox_kamar.getSelectedItem() == null || this.combox_mahas.getSelectedItem() == null){
            jLabel4.setText("");
        }else{
        Mahasiswa m = null;
        Asrama as = null;
        a.connect("localhost", "db_asrama", "pbo", "pbo");
        m = a.getmahasbynama(this.combox_mahas.getSelectedItem().toString());
        as = a.getasramabynama(this.combox_asrama.getSelectedItem().toString());
        a.addalloc(as.getId(), this.combox_kamar.getSelectedItem().toString(), m.getNim(), m.getNama(), as.getNama_asrama());
        jLabel4.setText("Success !");
        a.disconnect();
        }
        
        refreshbox();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void combox_asramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combox_asramaActionPerformed
        // TODO add your handling code here:
        refresh();
        int i = 0 ;
        Integer i2 = 1;
        int kamar = 0;
        while (i <this.max_asrm){
            if(this.combox_asrama.getSelectedItem() == null){
                
            }else if( asrm.get(i).getNama_asrama().equals(this.combox_asrama.getSelectedItem().toString())){
                kamar = Integer.parseInt(asrm.get(i).getJumlah_kamar());
               while(i2 <= kamar){
                   this.combox_kamar.addItem( (i2).toString() );
                   i2++; 
               }
            
            }
            i++;
        }
        
    }//GEN-LAST:event_combox_asramaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alokasi_Alok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alokasi_Alok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alokasi_Alok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alokasi_Alok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alokasi_Alok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combox_asrama;
    private javax.swing.JComboBox<String> combox_kamar;
    private javax.swing.JComboBox<String> combox_mahas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
