/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyek_pbo;
import proyek_pbo.DbHandler;
import java.util.ArrayList;
import java.util.List;
import proyek_pbo.Keasramaan;

/**
 *
 * @author kylex
 */
public class Asrama_JFrame_add extends javax.swing.JFrame {
    DbHandler a = new DbHandler();
    List<Keasramaan> kemahasiswaan = new ArrayList<Keasramaan>();
    int idx = 0;
    int max = 0;
    
    
    /**
     * Creates new form Asrama_JFrame
     */
    
    
    
    public Asrama_JFrame_add() {
        initComponents();
        this.pembina_combo.removeAllItems();
        a.connect("localhost", "db_asrama", "pbo", "pbo");
        kemahasiswaan = a.getallkemahas();
        max = a.counter;
        while(idx < max){
            this.pembina_combo.addItem(kemahasiswaan.get(idx).getNama());
            idx++;
        }
        this.success.setText("");
        this.req4.setText("");
        this.req5.setText("");
        this.req6.setText("");
        this.req7.setText("");
        this.req8.setText("");
        
        
        
        
        a.disconnect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        id_asrama_search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nama_asrama_search = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        labrrel = new javax.swing.JLabel();
        jlh_kamar_search = new javax.swing.JTextField();
        kapasitas_search = new javax.swing.JTextField();
        aasas = new javax.swing.JLabel();
        pembina_combo = new javax.swing.JComboBox<>();
        pembina_search = new javax.swing.JLabel();
        req4 = new javax.swing.JLabel();
        req5 = new javax.swing.JLabel();
        req6 = new javax.swing.JLabel();
        req7 = new javax.swing.JLabel();
        req8 = new javax.swing.JLabel();
        success = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tambah Asrama");

        jLabel1.setText("ID Asrama :");

        jLabel2.setText("Nama Asrama : ");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        labrrel.setText("Jumlah Kamar :");

        kapasitas_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kapasitas_searchActionPerformed(evt);
            }
        });

        aasas.setText("Kapasitas");

        pembina_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pembina_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembina_comboActionPerformed(evt);
            }
        });

        pembina_search.setText("Pembina");

        req4.setForeground(new java.awt.Color(255, 0, 0));
        req4.setText("Required!");

        req5.setForeground(new java.awt.Color(255, 0, 0));
        req5.setText("Required!");

        req6.setForeground(new java.awt.Color(255, 0, 0));
        req6.setText("Required!");

        req7.setForeground(new java.awt.Color(255, 0, 0));
        req7.setText("Required!");

        req8.setForeground(new java.awt.Color(255, 0, 0));
        req8.setText("Required!");

        success.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        success.setForeground(new java.awt.Color(51, 153, 0));
        success.setText("Success !");

        jLabel3.setText("Asrama");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(success)
                        .addGap(283, 283, 283))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(id_asrama_search, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pembina_search)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pembina_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(aasas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                        .addComponent(kapasitas_search, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labrrel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jlh_kamar_search, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(35, 35, 35)
                                        .addComponent(nama_asrama_search, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(req6)
                            .addComponent(req4)
                            .addComponent(req5)
                            .addComponent(req7)
                            .addComponent(req8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(addButton)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(id_asrama_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(req4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama_asrama_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(req5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlh_kamar_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labrrel)
                    .addComponent(req6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aasas)
                    .addComponent(req7)
                    .addComponent(kapasitas_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pembina_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pembina_search)
                    .addComponent(req8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(success)
                    .addComponent(addButton))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pembina_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembina_comboActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_pembina_comboActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        if(this.nama_asrama_search.getText().isEmpty() ){
            this.req5.setText("Required !");
        }else{
            this.req5.setText("");
        }
        
        if(this.id_asrama_search.getText().isEmpty() ){
            this.req4.setText("Required !");
        }else{
            this.req4.setText("");
        }
        
        if(this.jlh_kamar_search.getText().isEmpty() ){
            this.req6.setText("Required !");
        }else{
            this.req6.setText("");
        }
        
         if(this.kapasitas_search.getText().isEmpty() ){
            this.req7.setText("Required !");
        }else{
            this.req7.setText("");
        }
        
        if(this.pembina_combo.getSelectedItem().toString().isEmpty() ){
            this.req8.setText("Required !");
        }else{
            this.req8.setText("");
        }
        
        a.connect("localhost", "db_asrama", "pbo", "pbo");
        if( !"Required !".equals(this.req4.getText()) && !"Required !".equals(this.req5.getText()) && !"Required !".equals(this.req6.getText()) && !"Required !".equals(this.req7.getText()) && !"Required !".equals(this.req8.getText())){
            a.addAsrama(this.id_asrama_search.getText(), this.nama_asrama_search.getText(), this.jlh_kamar_search.getText(),this.kapasitas_search.getText(), this.pembina_combo.getSelectedItem().toString());
            this.success.setText("Success !");
            this.id_asrama_search.setText("");
            this.jlh_kamar_search.setText("");
            this.kapasitas_search.setText("");
            this.nama_asrama_search.setText("");
            
        }else{
            this.success.setText("");
            
        }
        a.disconnect();
        
        
        
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void kapasitas_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kapasitas_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kapasitas_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asrama_JFrame_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asrama_JFrame_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asrama_JFrame_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asrama_JFrame_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Asrama_JFrame_add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aasas;
    private javax.swing.JButton addButton;
    private javax.swing.JTextField id_asrama_search;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jlh_kamar_search;
    private javax.swing.JTextField kapasitas_search;
    private javax.swing.JLabel labrrel;
    private javax.swing.JTextField nama_asrama_search;
    private javax.swing.JComboBox<String> pembina_combo;
    private javax.swing.JLabel pembina_search;
    private javax.swing.JLabel req4;
    private javax.swing.JLabel req5;
    private javax.swing.JLabel req6;
    private javax.swing.JLabel req7;
    private javax.swing.JLabel req8;
    private javax.swing.JLabel success;
    // End of variables declaration//GEN-END:variables
}
