/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyek_pbo;
import proyek_pbo.*;

/**
 *
 * @author kylex
 */
public class Home extends javax.swing.JFrame {
    
    Asrama_JFrame_Home asrm = new Asrama_JFrame_Home();
    Keasramaan_Home keasrm = new Keasramaan_Home();
    Mahasiswa_Home mahas = new Mahasiswa_Home();
    Alokasi_Home alloc = new Alokasi_Home();
    /**
     * Creates new form View_Keasramaan
     */
    public Home() {
        initComponents();
        asrm.setDefaultCloseOperation(HIDE_ON_CLOSE);
        keasrm.setDefaultCloseOperation(HIDE_ON_CLOSE);
        mahas.setDefaultCloseOperation(HIDE_ON_CLOSE);
        alloc.setDefaultCloseOperation(HIDE_ON_CLOSE);
        
        //asrm.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        keasramaanButton = new javax.swing.JButton();
        mahasiswaButton = new javax.swing.JButton();
        alokasiButton = new javax.swing.JButton();
        asramaButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        keasramaanButton.setText("Keasramaan");
        keasramaanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keasramaanButtonActionPerformed(evt);
            }
        });

        mahasiswaButton.setText("Mahasiswa");
        mahasiswaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mahasiswaButtonActionPerformed(evt);
            }
        });

        alokasiButton.setText("Data Alokasi");
        alokasiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alokasiButtonActionPerformed(evt);
            }
        });

        asramaButton.setText("Asrama");
        asramaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asramaButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Select Menu ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(asramaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alokasiButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(keasramaanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mahasiswaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keasramaanButton)
                    .addComponent(asramaButton))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mahasiswaButton)
                    .addComponent(alokasiButton))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void asramaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asramaButtonActionPerformed
        // TODO add your handling code here:
        asrm.setVisible(true);
        
        
    }//GEN-LAST:event_asramaButtonActionPerformed

    private void mahasiswaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mahasiswaButtonActionPerformed
        // TODO add your handling code here:
        mahas.setVisible(true);
    }//GEN-LAST:event_mahasiswaButtonActionPerformed

    private void keasramaanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keasramaanButtonActionPerformed
        // TODO add your handling code here:
        keasrm.setVisible(true);
    }//GEN-LAST:event_keasramaanButtonActionPerformed

    private void alokasiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alokasiButtonActionPerformed
        // TODO add your handling code here:
        alloc.setVisible(true);
        
    }//GEN-LAST:event_alokasiButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alokasiButton;
    private javax.swing.JButton asramaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton keasramaanButton;
    private javax.swing.JButton mahasiswaButton;
    // End of variables declaration//GEN-END:variables
}
