/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyek_pbo;

import proyek_pbo.*;
import java.util.List;
import java.util.ArrayList;

/**
 *
 * @author kylex
 */
public class Mahasiswa_JFrame_search extends javax.swing.JFrame {

    DbHandler a = new DbHandler();

    /**
     * Creates new form Mahasiswa_JFrame
     */
    public Mahasiswa_JFrame_search() {
        initComponents();
        label_found.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nimsearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        info_nama = new javax.swing.JLabel();
        info_kelamin = new javax.swing.JLabel();
        info_prodi = new javax.swing.JLabel();
        info_angkatan = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        info_asrama = new javax.swing.JLabel();
        info_kamar = new javax.swing.JLabel();
        label_found = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Search Student Information");

        jLabel2.setText("NIM :");

        nimsearch.setForeground(new java.awt.Color(102, 102, 102));
        nimsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimsearchActionPerformed(evt);
            }
        });

        jLabel3.setText("Information ");

        info_nama.setText("Nama :");

        info_kelamin.setText("Jenis Kelamin :");

        info_prodi.setText("Prodi : ");

        info_angkatan.setText("Angkatan : ");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        info_asrama.setText("Nama Asrama :");

        info_kamar.setText("No Kamar : ");

        label_found.setText("Not Found !");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(info_kamar)
                            .addComponent(info_asrama)
                            .addComponent(info_angkatan)
                            .addComponent(info_prodi)
                            .addComponent(info_kelamin)
                            .addComponent(info_nama)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nimsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(label_found))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nimsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(label_found))
                .addGap(18, 18, 18)
                .addComponent(info_nama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(info_kelamin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(info_prodi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(info_angkatan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(info_asrama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(info_kamar)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nimsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimsearchActionPerformed
        // TODO add your handling code here:

        nimsearch.setText("");


    }//GEN-LAST:event_nimsearchActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        if ("".equals(nimsearch.getText())) {
            label_found.setText("");
            this.info_nama.setText("Nama : ");
            this.info_kelamin.setText("Jenis Kelamin : ");
            this.info_prodi.setText("Prodi : ");
            this.info_angkatan.setText("Angkatan : ");
            this.info_asrama.setText("Nama Asrama : ");
            this.info_kamar.setText("No Kamar : ");
        } else {
            a.connect("localhost", "db_asrama", "pbo", "pbo");
            Alokasi allc = a.getallocbynim(nimsearch.getText());
            Mahasiswa mahas = a.getmahasbynim(nimsearch.getText());
            if (allc == null || mahas == null) {
                label_found.setText("Not Found !");
                this.info_nama.setText("Nama : ");
                this.info_kelamin.setText("Jenis Kelamin : ");
                this.info_prodi.setText("Prodi : ");
                this.info_angkatan.setText("Angkatan : ");
                this.info_asrama.setText("Nama Asrama : ");
                this.info_kamar.setText("No Kamar : ");
            } else {
                this.info_nama.setText("Nama : " + allc.getNama_Mahasiswa());
                this.info_kelamin.setText("Jenis Kelamin : " + mahas.getJenis_kelamin());
                this.info_prodi.setText("Prodi : " + mahas.getProdi());
                this.info_angkatan.setText("Angkatan : " + mahas.getAngkatan());
                this.info_asrama.setText("Nama Asrama : " + allc.getNama_Asrama());
                this.info_kamar.setText("No Kamar : " + allc.getID_Kamar());
                nimsearch.setText("");
            }

        }


    }//GEN-LAST:event_searchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa_JFrame_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa_JFrame_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa_JFrame_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa_JFrame_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mahasiswa_JFrame_search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel info_angkatan;
    private javax.swing.JLabel info_asrama;
    private javax.swing.JLabel info_kamar;
    private javax.swing.JLabel info_kelamin;
    private javax.swing.JLabel info_nama;
    private javax.swing.JLabel info_prodi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_found;
    private javax.swing.JTextField nimsearch;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
