/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyek_pbo;
import proyek_pbo.*;

/**
 *
 * @author kylex
 */
public class Mahasiswa_Add extends javax.swing.JFrame {
    DbHandler a = new DbHandler();
    
    /**
     * Creates new form Mahasiswa_add
     */
    
    
    
    public Mahasiswa_Add() {
        initComponents();
        this.combox_sex.removeAllItems();
        this.combox_sex.addItem("L");
        this.combox_sex.addItem("P");
        this.req1.setText("");
        this.req2.setText("");
        this.req3.setText("");
        this.req4.setText("");
        this.req5.setText("");
        this.success1.setText("");
        this.combox_prodi.removeAllItems();
        this.combox_prodi.addItem("S1 Sistem Informasi");
        this.combox_prodi.addItem("S1 Manajemen Rekayasa");
        this.combox_prodi.addItem("S1 Teknik Informatika");
        this.combox_prodi.addItem("S1 Teknik Elektro");
        this.combox_prodi.addItem("S1 Teknik Bioproses");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nim_search = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        req1 = new javax.swing.JLabel();
        label_nama = new javax.swing.JLabel();
        req2 = new javax.swing.JLabel();
        label_nik = new javax.swing.JLabel();
        req3 = new javax.swing.JLabel();
        label_hp = new javax.swing.JLabel();
        req4 = new javax.swing.JLabel();
        label_sex = new javax.swing.JLabel();
        success1 = new javax.swing.JLabel();
        nama_search = new javax.swing.JTextField();
        req5 = new javax.swing.JLabel();
        label_sex1 = new javax.swing.JLabel();
        angkatan_search = new javax.swing.JTextField();
        combox_sex = new javax.swing.JComboBox<>();
        combox_prodi = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        req1.setForeground(new java.awt.Color(255, 0, 0));
        req1.setText("Required!");

        label_nama.setText("NIM :");

        req2.setForeground(new java.awt.Color(255, 0, 0));
        req2.setText("Required!");

        label_nik.setText("Nama :");

        req3.setForeground(new java.awt.Color(255, 0, 0));
        req3.setText("Required!");

        label_hp.setText("Jenis Kelamin :");

        req4.setForeground(new java.awt.Color(255, 0, 0));
        req4.setText("Required!");

        label_sex.setText("Prodi :");

        success1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        success1.setForeground(new java.awt.Color(0, 153, 0));
        success1.setText("Success !");

        req5.setForeground(new java.awt.Color(255, 0, 0));
        req5.setText("Required!");

        label_sex1.setText("Angkatan :");

        combox_sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combox_sex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combox_sexActionPerformed(evt);
            }
        });

        combox_prodi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Data Mahasiswa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(success1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_sex1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label_nama)
                                            .addComponent(label_hp)
                                            .addComponent(label_nik)
                                            .addComponent(label_sex))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(combox_prodi, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(nama_search, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                                            .addComponent(combox_sex, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addComponent(nim_search, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(angkatan_search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(req1)
                                    .addComponent(req2)
                                    .addComponent(req3)
                                    .addComponent(req4)
                                    .addComponent(req5)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(req1)
                    .addComponent(nim_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nama))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nik)
                    .addComponent(req2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_hp)
                    .addComponent(combox_sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(req3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(req4)
                    .addComponent(combox_prodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_sex))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(addButton)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(angkatan_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_sex1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(req5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(success1)
                        .addGap(21, 21, 21))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        
        if(this.nim_search.getText().isEmpty() ){
            this.req1.setText("Required !");
        }else{
            this.req1.setText("");
        }
        
        if(this.nama_search.getText().isEmpty() ){
            this.req2.setText("Required !");
        }else{
            this.req2.setText("");
        }
        
        if(this.combox_prodi.getSelectedItem().toString().isEmpty() ){
            this.req4.setText("Required !");
        }else{
            this.req4.setText("");
        }
        
         if(this.angkatan_search.getText().isEmpty() ){
            this.req5.setText("Required !");
        }else{
            this.req5.setText("");
        }
        
        if(this.combox_sex.getSelectedItem().toString().isEmpty() ){
            this.req3.setText("Required !");
        }else{
            this.req3.setText("");
        }
        
        a.connect("localhost", "db_asrama", "pbo", "pbo");
        if( !"Required !".equals(this.req1.getText()) && !"Required !".equals(this.req2.getText()) && !"Required !".equals(this.req3.getText()) && !"Required !".equals(this.req4.getText()) && !"Required !".equals(this.req5.getText())){
            a.addMahas(this.nim_search.getText(), this.nama_search.getText(), this.combox_sex.getSelectedItem().toString(),this.combox_prodi.getSelectedItem().toString(),this.angkatan_search.getText());
            this.success1.setText("Success !");
            this.angkatan_search.setText("");
            this.nama_search.setText("");
            this.nim_search.setText("");
            
            
            
        }else{
            this.success1.setText("");
            
        }
        a.disconnect();
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void combox_sexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combox_sexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combox_sexActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mahasiswa_Add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField angkatan_search;
    private javax.swing.JComboBox<String> combox_prodi;
    private javax.swing.JComboBox<String> combox_sex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label_hp;
    private javax.swing.JLabel label_nama;
    private javax.swing.JLabel label_nik;
    private javax.swing.JLabel label_sex;
    private javax.swing.JLabel label_sex1;
    private javax.swing.JTextField nama_search;
    private javax.swing.JTextField nim_search;
    private javax.swing.JLabel req1;
    private javax.swing.JLabel req2;
    private javax.swing.JLabel req3;
    private javax.swing.JLabel req4;
    private javax.swing.JLabel req5;
    private javax.swing.JLabel success1;
    // End of variables declaration//GEN-END:variables
}
